services:
  otus-kafka-ui:
    build: 
      context: ./ui
      args:
        STOREPASS: ${KAFKA_UI_STOREPASS}
    image: otus-kafka-ui
    container_name: otus-kafka-ui
    ports:
      - "8282:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTERS_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_CLUSTERS_BOOTSTRAPSERVERS}
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_CLIENT_DNS_LOOKUP: use_all_dns_ips
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER_LOGIN}" password="${KAFKA_USER_PASSWORD}";'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /truststore/truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_UI_STOREPASS}

  otus-ksqldb-server:
    build:
      context: ./ksqldb
      args:
        STOREPASS: ${KSQLDB_STOREPASS}
    image: otus-ksqkdb-server
    container_name: otus-ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_OPTS: "-Dconfluent.support.metrics.enable=false"
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: ${KAFKA_CLUSTERS_BOOTSTRAPSERVERS}
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_SECURITY_PROTOCOL: SASL_SSL
      KSQL_SASL_MECHANISM: PLAIN
      KSQL_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER_LOGIN}" password="${KAFKA_USER_PASSWORD}";'
      KSQL_SSL_TRUSTSTORE_LOCATION: /truststore/truststore.jks
      KSQL_SSL_TRUSTSTORE_PASSWORD: ${KSQLDB_STOREPASS}

  otus-ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.7.1
    container_name: otus-ksqldb-cli
    entrypoint: /bin/sh
    tty: true


        





